name: Build Codes and SDCards

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - uses: actions/checkout@v3

    - name: Config and Build Codes
      run: |
        sh ./build-linux.sh
        sudo bash ./sdcard-linux.sh

    - name: Upload SDCards
      uses: actions/upload-artifact@v2
      with:
        name: SDCard
        path: |
          ./sdcard1.raw
          ./sdcard2.raw
