name: Build Codes and SDCards

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - uses: actions/checkout@v3

    - name: Verify installation
      run: |
        echo 'int main(){}' > main.c
        powerpc-eabi-gcc -mcpu=750 -mhard-float main.c -o main.elf

    - name: Config and Build Codes
      run: sh ./build-linux.sh
